language: go

go:
  - 1.7

# Setting sudo access to false will let Travis CI use containers rather than
# VMs to run the tests. For more details see:
# - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# - http://docs.travis-ci.com/user/workers/standard-infrastructure/
sudo: false

# The default script is go test -v ./... which will test everything
# in the vendor directory. We don't need to test all dependent packages.
# Only testing this project.
script:
  - make
